CREATE DATABASE ycyw_db;
USE ycyw_db;
CREATE TABLE `VEHICLE_CATEGORIES` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `category` VARCHAR(10),
  `name` VARCHAR(20)
);

CREATE TABLE `RENTALS` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `start_day` DATETIME,
  `day_nb` INT,
  `offer_id` BIGINT,
  `client_user_id` BIGINT,
  `agency_id_end` BIGINT,
  `rental_price` INT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `AGENCIES` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `address` VARCHAR(100),
  `postal_code` BIGINT,
  `city` VARCHAR(40),
  `country` VARCHAR(40),
  `email` VARCHAR(60),
  `phone_nb` VARCHAR(20)
);

CREATE TABLE `USERS` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `first_name` VARCHAR(30),
  `last_name` VARCHAR(30),
  `birth_date` DATE,
  `address` VARCHAR(100),
  `email` VARCHAR(255),
  `password` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `SUPPORT_USERS` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `first_name` VARCHAR(30),
  `last_name` VARCHAR(30),
  `agency_id` BIGINT,
  `email` VARCHAR(255),
  `password` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `DISCUSSIONS` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT, 
  `client_user_id` BIGINT,
  `subject` VARCHAR(150),
  `rental_id` BIGINT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `MESSAGES` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT, 
  `discussion_id` BIGINT,
  `client_user_id` BIGINT,
  `support_user_id` BIGINT,
  `message` VARCHAR(500),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `OFFERS` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT, 
  `agency_id` BIGINT,
  `vehicle_category_id` BIGINT,
  `price_per_day` float,
  `currency` VARCHAR(10)
);

ALTER TABLE `SUPPORT_USERS` ADD FOREIGN KEY (`agency_id`) REFERENCES `AGENCIES` (`id`);
ALTER TABLE `DISCUSSIONS` ADD FOREIGN KEY (`client_user_id`) REFERENCES `USERS` (`id`);
ALTER TABLE `DISCUSSIONS` ADD FOREIGN KEY (`rental_id`) REFERENCES `RENTALS` (`id`);
ALTER TABLE `MESSAGES` ADD FOREIGN KEY (`discussion_id`) REFERENCES `DISCUSSIONS` (`id`);
ALTER TABLE `MESSAGES` ADD FOREIGN KEY (`client_user_id`) REFERENCES `USERS` (`id`);
ALTER TABLE `MESSAGES` ADD FOREIGN KEY (`support_user_id`) REFERENCES `USERS` (`id`);
ALTER TABLE `RENTALS` ADD FOREIGN KEY (`client_user_id`) REFERENCES `USERS` (`id`);
ALTER TABLE `RENTALS` ADD FOREIGN KEY (`agency_id_end`) REFERENCES `AGENCIES` (`id`);
ALTER TABLE `RENTALS` ADD FOREIGN KEY (`offer_id`) REFERENCES `OFFERS` (`id`);
ALTER TABLE `OFFERS` ADD FOREIGN KEY (`agency_id`) REFERENCES `AGENCIES` (`id`);
ALTER TABLE `OFFERS` ADD FOREIGN KEY (`vehicle_category_id`) REFERENCES `VEHICLE_CATEGORIES` (`id`);

INSERT INTO SUPPORT_USERS (first_name, last_name, email, password)
VALUES ('Admin', 'admin', 'admin@email.com', '$2a$10$KemtyIIZ3XSAZJtb6glIN.bqEyYzkmtQxmSHpeE/URhYpdFQQ9az.');